name: mcMMO
main: com.gmail.nossr50.mcMMO
version: 1.0.34
commands:
    mcc:
        description:
    mcmmo:
        description:
    mctop:
        description:
    addxp:
        description:
    mcability:
        description:
    mcrefresh:
        description:
    mcgod:
        description:
    stats:
        description:
    mmoedit:
        description:
    ptp:
        description:
    party:
        description:
    myspawn:
        description:
    whois:
        description:
    invite:
        description:
    accept:
        description:
    clearmyspawn:
        description:
    mmoupdate:
        description:
    p:
        description:
    excavation:
        description:
    herbalism:
        description:
    mining:
        description:
    woodcutting:
        description:
    axes:
        description:
    archery:
        description:
    swords:
        description:
    taming:
        description:
    unarmed:
        description:
    acrobatics:
        description:
    repair:
        description:
    a:
        description:
    setmyspawn:
        description:
    sorcery:
        description: